### ISSUE TITLE
NovaServiceProvider - boot - access to tenancy

### ISSUE THREAD

**Issue by kerbs-ns** [stancl/tenancy#1093]
### Bug description

NovaServiceProvider.php

 public function boot()
    {
        parent::boot();

 dd(tenancy()->initialized);

is always false

### Steps to reproduce

Setup tenancy with nova. Shared nova central/tenant using your premium docs

### Expected behavior

Should tenancy available in NovaServiceProvider->boot method.

Seems to be bug ?!

it is awailable on other methods and works as expected.

Have installed, am sub on your tutorials, with diff account.

Setup is shared nova for central/tenant.

### Laravel version

v9.52.4

### stancl/tenancy version

v3.7.0

**Comment by stancl** [comment]
In general, `tenancy()` is never available in service providers. It's always initialized **much later** in the request lifecycle than service providers. The `resources()` method in Nova SP is one of the only exceptions since it's not part of the usual service provider logic but rather a custom method that is called later in the lifecycle.

**Comment by kerbs-ns** [comment]
First thanks on that fast replay !!!!

That was my suspicion.

So issue is https://nova.laravel.com/docs/4.0/customization/menus.html#customizing-the-main-menu

any customization of menu is required to be in boot.

I have put it in resources and it works.. interesting. So kinda hacky :) seems to work
