### ISSUE TITLE
Generic model type "returned" by Tenant::all() raises a warning in Larastan/PHPstan

### ISSUE THREAD

**Issue by kmcluckie** [stancl/tenancy#1109]
### Bug description

When the Tenant model is inherited from and the `all()` method is called, it maps to generic `Illuminate\Database\Eloquent\Model` objects, rather than the actual model.

### Steps to reproduce

Create a model class that inherits from `Tenant`. In my case it is `Organisation`.
  
    class Organisation extends Tenant implements TenantContract
    {
        use HasDomains, HasFactory;
        ...
    }

Now, do something that expects `Organisation::all()` to return a collection of `Organisation` objects:

    foreach (Organisation::all() as $organisation) {
        $this->doThing->execute($organisation); // execute() signature expects and Organisation model
    }

PHPstan reports:

    Parameter #1 $organisation of method                               
    Domain\Organisation\Actions\DoThing::execute() expects  
    Domain\Organisation\Models\Organisation,                           
    Illuminate\Database\Eloquent\Model given.

The Intelephense extension in VS Code confirms this.

### Expected behavior

`Organisation:all()` should provide a collection that iterates over `Organisation` models.

This looks like it is just a matter of PHPDoc annotations, but I'm not familiar enough to resolve it myself.

### Laravel version

10.5.1

### stancl/tenancy version

3.7.0

**Comment by stancl** [comment]
I'm open to accepting a PR that fixes this, though going to close this issue as it's not really a bug.

We provide *some* typehints that are generally useful in most IDEs but they may not be perfect in the context of static analysis. Ideally we'd have perfect typehints but I'm not sure myself what can be done here since we have interfaces, default models that *can* be used but don't have to be used, and then the actual models in the application.
