### ISSUE TITLE
Tenant migrations add tables to the central db when using DATABASE_URL in the .env file

### ISSUE THREAD

**Issue by michelterstege81** [stancl/tenancy#1112]
### Bug description

When I deploy my app on DigitalOcean with a managed database I noticed that the tables for the tenant were created in the central db.

The issue occurs when using DATABASE_URL as a connection string in the .env file.

When using the individual parameters (DB_HOST, DB_PORT etc.) the issue does not occur.

### Steps to reproduce

Use DATABASE_URL to connect to the db in the .env file.

### Expected behavior

Tenant tables should be created in the tenant db.

### Laravel version

10

### stancl/tenancy version

3.7

**Comment by stancl** [comment]
That's probably because tenancy sets the individual parts of the DB connection (as in the host, port, etc). So if a URL is set as well, it takes precedence over those and the values set by tenancy aren't used.

Don't think we'll be changing how this works in the code, but we might add a note to the docs.

**Comment by Parables** [comment]
@stancl please do add this to the docs... 
I got stuck on this for weeks and didn't realise that the DATABASE_URL was the cause until I found this issue

**Comment by stancl** [comment]
Was thinking where in the docs I could add this so that people would find it, but since this just leads to unpredictable behavior in prod, I think it might be still difficult for people to find it in docs. The DatabaseTenancyBootstrapper page/section could work, but would probably still be missed.

So I'm thinking about also throwing an exception when `DATABASE_URL` is set. Would lead to every tenant route in prod becoming unusable (500 error) instead of writing to the wrong DB.

`DATABASE_URL` is not supported and there aren't really plans to support it, our package expects to work with individual parts of the DB config, so this might be the best solution to the problem.

**Comment by stancl** [comment]
Exception added in v4
