### ISSUE TITLE
Wrong domain url when on queue

### ISSUE THREAD

**Issue by GithubEficienciaTributaria** [stancl/tenancy#1210]
### Bug description

I've created a database queue and configured it to work with the library but when I try to generate a temporary secure url, or just to check the current domain with (url()->current()), both keeps returning a link with the central url instead of the tenant domain.
If I try to get the current tenant responsible with the job, the tenant returns successfully.
I have included a screenshot to help showing the error.

![error](https://github.com/archtechx/tenancy/assets/133399447/c999e6a9-3cbe-4964-a967-7cb2e9bddb6e)

### Steps to reproduce

1- Configure laravel queue database to work with laravel tenancy with domain verification.
2- Create a simple job and put a dd to check a temp url, current url and the tenant for the given queue
3- Execute the queue worker
4- Dispatch the job

Configure laravel queue to work with laravel tenancy, create a simple job and try to generate an url, or access the current url with url()->current().

### Expected behavior

The job should be able to generate a temporary signed url or get the current url based in the domain from the tenant that dispatched the job.

Example: http://test.localhost/etc...
Current: http://localhost/etc..

### Laravel version

10.10

### stancl/tenancy version

3.7

**Comment by stancl** [comment]
You need to manually update your `app.url`, either in the config or something like forcing the URL root on `app('url')`.

This isn't a bug since tenancy cannot solve this for you out of the box — tenants can have multiple (sub)domains and there may be multiple central domains, so the package cannot determine how you want to build your tenant URLs.

In v4, we have a bootstrapper for making this a bit simpler, but it still requires that you configure it to format URLs based on how *your* application works.

**Comment by GithubEficienciaTributaria** [comment]
Thank you for the help.
