### ISSUE TITLE
Make runForMultiple yield the callbacks return

### ISSUE THREAD

**Issue by gisostallenberg** [stancl/tenancy#1213]
#### Description
It would be nice to have the results of the callback calls in `runForMultiple` in a Generator, so the results of the callback can be inspected.

```diff
--- src/Tenancy.php.orig	2024-04-14 10:12:18.000000000 +0200
+++ src/Tenancy.php	2024-04-24 11:52:06.430487669 +0200
@@ -133,7 +133,7 @@
      *
      * @param Tenant[]|\Traversable|string[]|null $tenants
      * @param callable $callback
-     * @return void
+     * @return \Generator<mixed>
      */
     public function runForMultiple($tenants, callable $callback)
     {
@@ -157,7 +157,7 @@
             }
 
             $this->initialize($tenant);
-            $callback($tenant);
+            yield $callback($tenant);
         }
 
         if ($originalTenant) {
```

For example, this will make it possible to give a proper status code when a console command runs for multiple tenants.
```php
    public function handle(): int
    {
        /** @var (iterable<string>&\Traversable)|null $tenants */
        $tenants = $this->option('tenants');
        foreach (tenancy()->runForMultiple($tenants, $this->handleTenant(...)) as $result) {
            if ($result === self::FAILURE) {
                return self::FAILURE;
            }
        }

        return self::SUCCESS;
    }
```

Would you be interested in a PR?

**Comment by stancl** [comment]
The change to a generator would mean in that in your example, if you had say 10 tenants and `$result === self::FAILURE` on the second tenant, tenancy would not loop through the remaining tenants since you did a return and didn't use the rest of the generator?

**Comment by stancl** [comment]
Ah also realized this addresses `runForMultiple()` return values in general, I thought I had already changed it to an array but seems like not.

I can see the benefits of yield, but *any* return value would be an improvement. For instance with arrays I'd prefer to have them keyed by the tenant keys:
```diff
diff --git a/src/Tenancy.php b/src/Tenancy.php
index c1c62916..08b940da 100644
--- a/src/Tenancy.php
+++ b/src/Tenancy.php
@@ -185,9 +185,12 @@ class Tenancy
      * Run a callback for multiple tenants.
      * More performant than running $tenant->run() one by one.
      *
+     * @template T
      * @param array<Tenant>|array<string|int>|\Traversable|string|int|null $tenants
+     * @param Closure(Tenant): T $callback
+     * @return array<string|int, T>
      */
-    public function runForMultiple($tenants, Closure $callback): void
+    public function runForMultiple($tenants, Closure $callback): array
     {
         // Convert null to all tenants
         $tenants = is_null($tenants) ? $this->model()->cursor() : $tenants;
@@ -203,6 +206,8 @@ class Tenancy

         $originalTenant = $this->tenant;

+        $results = [];
+
         foreach ($tenants as $tenant) {
             if (! $tenant instanceof Tenant) {
                 $tenant = $this->find($tenant);
@@ -210,7 +215,7 @@ class Tenancy

             /** @var Tenant $tenant */
             $this->initialize($tenant);
-            $callback($tenant);
+            $results[$tenant->getTenantKey()] = $callback($tenant);
         }

         if ($originalTenant) {
@@ -218,6 +223,8 @@ class Tenancy
         } else {
             $this->end();
         }
+
+        return $results;
     }

     /**
```
so that you can do:
```php
foreach (tenancy()->runForMultiple($this->callback(...)) as $tenant => $result) {
    //
}
```

Since we had a `void` return value until now, we could move to a generator more easily than if we had been using an array before, but I'm thinking:
1. What advantages does a generator have over an array in your case, is it just resource usage?
2. Is there a way we could provide the tenant, besides just returning a `[$tenant, $result]` tuple
3. Wouldn't this make it so that any existing `tenancy()->runForMultiple()` calls don't do anything on their own until iterated, which could be a hard to spot breaking change?

I'd also like to note that originally, `runForMultiple()` was intended to be a more performant version of:
```php
foreach ($tenants as $tenant) {
    $tenant->run($callback);
}
```
However, as the package developed, the things that were making `runForMultiple()` faster (namely not calling `end()` and only going straight to `initialize()` when switching tenants iirc) were removed so that our bootstrappers have better consistency guarantees.

**Comment by gisostallenberg** [comment]
`yield` can also give a key

```diff
--- src/Tenancy.php.orig	2024-04-14 10:12:18.000000000 +0200
+++ src/Tenancy.php	2024-04-24 11:52:06.430487669 +0200
@@ -133,7 +133,7 @@
      *
      * @param Tenant[]|\Traversable|string[]|null $tenants
      * @param callable $callback
-     * @return void
+     * @return \Generator<string, mixed>
      */
     public function runForMultiple($tenants, callable $callback)
     {
@@ -157,7 +157,7 @@
             }
 
             $this->initialize($tenant);
-            $callback($tenant);
+            yield $tenant->getTenantKey() => $callback($tenant);
         }
 
         if ($originalTenant) {
```

**Comment by gisostallenberg** [comment]
I think that your point 3 is indeed something I did not consider.

**Comment by gisostallenberg** [comment]
I'm closing this because of point 3
