### ISSUE TITLE
SQLSTATE[HY000] [1040] Too many connections

### ISSUE THREAD

**Issue by hackeresq** [stancl/tenancy#1237]
### Bug description

Each tenant has their own MySQL database. 

This has worked perfect for several years, but with some recent growth (just over 70 tenants), I've run into several situations now where MySQL is overloaded with too many connections. This has happened during deploys (when running DB migrations for each tenant) or when otherwise needing to run the same action on each database such as updating certain configurations. 

The error is:
```
SQLSTATE[HY000] [1040] Too many connections
```

### Steps to reproduce

This seems to be related to running the `runForMultiple` method. As mentioned above, I have ~70 tenants on a single AWS RDS database (so I can't simply increase max connections - this is determined programmatically based on available CPU).

### Expected behavior

Close the connection after each tenant is done? 

Seems like adding `DB::disconnect('tenant');` at the bottom of the callback for `runForMultiple` is solving this. 

Should the `runForMultiple` method automatically close the connection after each iteration is complete? 

### Laravel version

10.46

### stancl/tenancy version

3.7

**Comment by stancl** [comment]
Since this isn't a bug in the package but a support question, please use our Discord.

**Comment by hackeresq** [comment]
Happy to take this to the Discord, but I'd argue this is in fact a bug. 

My understanding is that Laravel only closes an active connection immediately before the HTTP response is sent back to the  client. 

In which case, each time this package's `runForMultiple` method runs there's an additional DB connection (and not closed).  This results in an n+1 for each tenant.

As I mentioned above, the solve for this is to close the tenant DB connection by running `DB::disconnect('tenant');` after each iteration of the `runForMultiple` method. In my opinion this should be included in the package - not something users should have to consider, especially since the ethos of this package is to make tenancy more or less transparent to the dev. 

[tenancy/src/Tenancy.php](https://github.com/archtechx/tenancy/blob/master/src/Tenancy.php):

```
    public function runForMultiple($tenants, callable $callback)
    {
        // Convert null to all tenants
        $tenants = is_null($tenants) ? $this->model()->cursor() : $tenants;

        // Convert incrementing int ids to strings
        $tenants = is_int($tenants) ? (string) $tenants : $tenants;

        // Wrap string in array
        $tenants = is_string($tenants) ? [$tenants] : $tenants;

        // Use all tenants if $tenants is falsey
        $tenants = $tenants ?: $this->model()->cursor();

        $originalTenant = $this->tenant;

        foreach ($tenants as $tenant) {
            if (! $tenant instanceof Tenant) {
                $tenant = $this->find($tenant);
            }

            $this->initialize($tenant);
            $callback($tenant);

            // check if the tenant model implements TenantWithDatabase  // <----- | suggestion
            DB::disconnect('tenant');                                                               // <----- |
        }

        if ($originalTenant) {
            $this->initialize($originalTenant);
        } else {
            $this->end();
        }
    }
}
```

Although, now that I've looked at this a bit deeper, when the DB is bootstrapped, it should be calling `$this->database->purge('tenant');` on the tenant's database. That _should_ be closing the excessive DB connections.

Perhaps there's some issue there.

**Comment by stancl** [comment]
I'd prefer to use Discord for this because we can communicate faster. There's many things to try here, such as persistent PDO connections. If you think something in the package can be improved, I can tell you where adding some code might help and then we can add that to the codebase. But it isn't a bug in the package, we're only talking about a concrete deployment and *maybe* that the package could handle it better.

> My understanding is that Laravel only closes an active connection immediately before the HTTP response is sent back to the client

This wouldn't be the case during deployments, since that's PHP CLI context, not php-fpm content. There's no HTTP response to be sent.

I don't remember exactly if PDO connections get closed the moment we switch to another tenant. The PDO connection instances do get destroyed, but perhaps in the CLI context the socket remains open and we could do a manual disconnect earlier.

If we added something like your code suggestion, we'd likely wrap it in a check to determine if we're in CLI context, or add some global config for this, since we do **not** want to do this in all scenarios necessarily. Connections remaining open can be a good thing too.

Again, these conversations are better suited for our Discord.
