### ISSUE TITLE
FilesystemTenancyBootstrapper - Prefix, not Suffix

### ISSUE THREAD

**Issue by Tickthokk** [stancl/tenancy#1258]
#### Description

In FilesystemTenancyBootstrapper, the suffix is being prepended (which is the preferred functionality), but the word for that is `prefix`, not `suffix`. The same is true for the config variable name.

```
$suffix = $this->app['config']['tenancy.filesystem.suffix_base'] . $tenant->getTenantKey();`
...
$this->app['config']['tenancy.filesystem.suffix_storage_path']
```

Database names offer both prefix and suffix options. It might also be worthwhile to offer both on filesystems too, but I'm not specifically requesting that.

#### Why this should be added

I think it's just an oversight, but fixing it would be an improvement :)

Thank you!

**Comment by stancl** [comment]
This terminology is a bit mixed in the config file due to how the different bootstrappers work, but in the case of the filesystem bootstrapper I think suffix should be correct?

The disk *is* suffixed with `suffix_base` + tenant. So the `suffix_base` is in a sense the prefix of `(suffix base) . tenant` but in the context of the disk it's a suffix.

**Comment by Tickthokk** [comment]
Ah, I get it now. Okay then :) Thanks for the package!
