### ISSUE TITLE
Is it possible to remove the subdomains from the URL in multiple databases?

### ISSUE THREAD

**Issue by alexv96** [stancl/tenancy#728]
I am writing because I have a doubt if it is possible to identify the domain without it appearing in the URL of the browsers.

For example currently I tested the library and I manage to have a central client tenancy.test but when I create a new tenant as it forces me to have the subdomain and the idea I have is that it is always the same url and that the subdomain will not be added, I do not know if you understand the idea.

Example
tenant 1: Jeremiah belongs to the subdomain app1.tenancy.test => I want him to be able to log in without problems and always navigate through tenancy.test/login or that the dashboard is seen as tenancy.test/dashboard and not as app1.tenancy.test/dashboard.

**Comment by Surt** [comment]
Maybe you could use https://tenancyforlaravel.com/docs/v3/tenant-identification/#request-data-identification but of course you still need to know wich tenant are you calling. I mean, since you are not recognizing it by the subdomain you must set a way to know for sure (a tenants selector along with the user login?)
