### ISSUE TITLE
Tenant Maintenance Secret

### ISSUE THREAD

**Issue by aeq-dev** [stancl/tenancy#757]
#### Description
Same as the main domain where we can enable maintenance with secret key in order to access to the app for admins for example,
is there a way to do that for tenant's admins

#### Why this should be added
Give the ability to tenant's admins to access to the app

**Comment by stein-j** [comment]
From what I can understand: The package doesn't uses the Laravel default maintenance mode, which doesn't surprises me because the way Laravel handle it is not tenant compatible.
This means this package would have to fully recreate Laravel maintenance mode, which could work... but not all features would be doable (like the --render option because this allows the render a page before Laravel boots, but for tenancy you need to boot Laravel).

_Small idea/lead:_ 
When Laravel is in maintenance mode, it can "except" routes defined in `PreventRequestsDuringMaintenance` middleware. Maybe the package could utilise this to use Laravel down feature and still allow some tenant. Though, I'm not convinced this is the best idea.

**Comment by stancl** [comment]
In which case would some tenants be in maintenance mode, but others not?

**Comment by stein-j** [comment]
@stancl to answer your question, I think there are many use case :

- A tenant that is used as a demo which is often reset, it needs to be put in maintenance mode temporally and alone
- You have a big update and want to put then into maintenance mode one by once instead of denying access to all tenants too long
- You have a tenant used for testing and do not want people to access it while you are working on it
- etc.

**Comment by stancl** [comment]
Right, I expressed myself poorly. I meant, in which case would some tenants be in maintenance mode, but others not, with a need for access via the URL secret.

For example the "_You have a big update and want to put then into maintenance mode one by once instead of denying access to all tenants too long_" point is just selective tenant maintenance mode. And the first point probably doesn't need a secret.

I can see why having some tenant accessible only for testing is good though.
