### ISSUE TITLE
VaporImage upload issue

### ISSUE THREAD

**Issue by bsormagec** [stancl/tenancy#765]
### Bug description

When I try to upload VaporImage on nova it returns an error to file not found 'tmp/xxxxxxxxx' but when I check s3 main directory "tmp/xxxxxxxx" file is there. But Storage can't copy file to the real directory.

### Steps to reproduce

Just installed saas package and added VaporImage component a resource and tried to upload file. It doesn't work

### Expected behavior

It need to work (save form) when i submit form.

### Laravel version

8.76.2

### stancl/tenancy version

^3.4

**Comment by stancl** [comment]
Going to reopen if more useful context is provided and others mention this.

**Comment by stf-alexander** [comment]
Having the same problem at the moment.

The [Laravel Vapor NPM Package](https://github.com/laravel/vapor-js) stores all temporary uploaded files from frontend in /tmp on AWS S3. The /tmp directory is automatically configured to purge any files older than 24 hours, which is really convenient, if the user doesn't submit the selected file.  
To save the temporary uploaded file after the user submits the form, the [Laravel Vapor docs](https://docs.vapor.build/1.0/resources/storage.html#file-uploads) suggest to copy the temporary uploaded file from /tmp directory to whatever directory. In this case it's moving the temporary file from /tmp to a tenant related directory.

Here's the problem: While in tenant context, the Storage facade cant access the /tmp directory, because the /tmp directory is located outside of the tenant related directory.

Is there any way to solve the problem ?
