### ISSUE TITLE
Mysql Error: 1615 Prepared statement needs to be re-prepared

### ISSUE THREAD

**Issue by imagina** [stancl/tenancy#940]
### Bug description

We are having a bug when the vendor try  to find the user in the database:

https://github.com/archtechx/tenancy/blob/3f3b7a3bffc2f37f66e317fc08acc47f9a85b5de/src/TenantDatabaseManagers/PermissionControlledMySQLDatabaseManager.php#L55

### Steps to reproduce

The server return this error:

 SQLSTATE[HY000]: General error: 1615 Prepared statement needs to be re-prepared (SQL: SELECT count(*) FROM mysql.user WHERE user = 'wtOf8yhvUAZJz0eH') /icms/vendor/laravel/framework/src/Illuminate/Database/Connection.php 712
 

### Expected behavior

 Many thanks in advance for your help.

### Laravel version

8.83.16

### stancl/tenancy version

3.5.1

**Comment by stancl** [comment]
Would need more reproduction instructions — this doesn't happen on my setup or the CI setup.

**Comment by schakko** [comment]
@imagina You might have hit [some configuration limits of your MySQL database](https://bugs.mysql.com/bug.php?id=42041):
If you run `SET GLOBAL table_definition_cache = 2500` (or some larger values like 3000, 4000) in the MySQL console, does the error goes away?

Otherwise, you can try to use the `PDO::ATTR_EMULATE_PRREPARES` option in your `database/config.php` like this:

```php
'connections' => [
    'tenant_template' => [
        'driver' => 'mysql',
        // ... 
        'options' => [
            PDO::ATTR_EMULATE_PREPARES => true,
        ],
    ],
```

**Comment by SagarNaliyapara** [comment]
Hi @stancl I'm frequently encountering similar error in production:

```
SQLSTATE[HY000]: General error: 1615 Prepared statement needs to be re-prepared (Connection: mysql_tenant, SQL: update tenants set ...)
```


It often occurs during tenant registration, especially while creating tenant databases or updating tenant records, which leads to registration failures. As a result, stale entries remain in the `tenants` table, blocking future registrations due to unique constraints (like email).

To handle this, I wrapped the registration flow in a DB transaction with a retry mechanism (0.5s delay), at least I don't have state entries but the issue still persists. My suspicion is that it may be related to MySQL's prepared statement caching (e.g., eviction or invalidation across multiple tenant connections).

Do you have any suggestions or insight on how this might be prevented, or how best to handle this within the package context?

Thanks in advance!
